### ISSUE TITLE
error in simulate_gene_trees.py

### ISSUE THREAD

**Issue by tsm-tsm** [ryanafolk/tree_utilities#1]
Hello,  I've encountered a problem I can't solve, and I hope to get your help. Excuse me.
When I run:
./tree_utilities-master/sampled_ancestornodes_to_branches.py astral-BS50.treefile 1000 example_gene_trees.tree

It displays the following:
Number of trees:
1
Number of taxa observed across all trees:
56
On tree:
0
Taxon number before:
81
Internal nodes are:
0.99
1
0.6
0.61
1
1
1
1
1
0.97
1
0.99
1
0.89
0.89
0.87
1
0.53
0.96
0.54
1
1
1
1
1
1
1
1
1
1
1
1
0.79
1
0.36
1
0.59
0.7
1
Taxon number after:
120

Then it will only generate a file named 1000, I don't know why

**Comment by ryanafolk** [comment]
Could you try removing clade labels?

Ryan

Ryan A. Folk
Assistant Professor and Herbarium Curator
Department of Biological Sciences
Mississippi State University
295 E. Lee Blvd.
P.O. Box GY
Mississippi State, MS 39762
http://www.ryanafolk.com

On May 4, 2024, at 1:50 AM, lilili ***@***.******@***.***>> wrote:



Hello,
when I run:
./tree_utilities-master/sampled_ancestornodes_to_branches.py astral-BS50.treefile 1000 example_gene_trees.tree

It displays the following:
Number of trees:
1
Number of taxa observed across all trees:
56
On tree:
0
Taxon number before:
81
Internal nodes are:
0.99
1
0.6
0.61
1
1
1
1
1
0.97
1
0.99
1
0.89
0.89
0.87
1
0.53
0.96
0.54
1
1
1
1
1
1
1
1
1
1
1
1
0.79
1
0.36
1
0.59
0.7
1
Taxon number after:
120

Then it will only generate a file named 1000, I don't know why

[&R] (C.rockii_GL,((((C.xichouensis_MLP_3,C.malipoensis_MLP_15,0.99:1e-06,0.99:1e-06)0.99:0.32243810307298676,(C.orthacantha_QZ,(C.chunii_FJS,C.platyacantha_YJ,1:1e-06,1:1e-06)1:0.37406668665060144,0.6:1e-06,0.6:1e-06)0.6:0.08409067707522011,0.61:1e-06,0.61:1e-06)0.61:0.11378267254495453,((C.kweichowensis_XDJ,(C.fabri_JFL,C.ceratacantha_TMS,1:1e-06,1:1e-06)1:0.30436039459550346,1:1e-06,1:1e-06)1:2.587731774271473,((C.nigrescens_HSD,((C.ferox_QSZ,(C.argyrophylla_LC,C.fleuryi_PDLZ,1:1e-06,1:1e-06)1:0.5601781358496789,1:1e-06,1:1e-06)1:1.121475080242024,(C.megaphylla_DW,(C.tonkinensis_JFL,C.jianfenglingensis_JFL_3,1:1e-06,1:1e-06)1:0.6447300811215705,0.97:1e-06,0.97:1e-06)0.97:0.20721818800412908,1:1e-06,1:1e-06)1:0.6733305377485906,0.99:1e-06,0.99:1e-06)0.99:0.38296347273396714,((C.lamontii_MS,(C.carlesii_FJS,C.eyrei_FJS,1:1e-06,1:1e-06)1:1.418149527361109,0.89:1e-06,0.89:1e-06)0.89:0.22233893815560762,((C.fargesii_FJS,C.amabilis_SS,0.89:1e-06,0.89:1e-06)0.89:0.11969034121265108,(C.echidnocarpa_DDG,C.ledongensis_JFL,0.87:1e-06,0.87:1e-06)0.87:0.1390794207845124,1:1e-06,1:1e-06)1:1.9286489324945448,0.53:1e-06,0.53:1e-06)0.53:0.06274525500552547,0.96:1e-06,0.96:1e-06)0.96:0.3364348729984316,0.54:1e-06,0.54:1e-06)0.54:0.07929213130289837,1:1e-06,1:1e-06)1:1.5327533203345407,(((C.tibetana_FJS,C.kawakamii_SCBG,1:1e-06,1:1e-06)1:0.3324394095779078,(C.fordii_HSD,C.hystrix_SS,1:1e-06,1:1e-06)1:0.3309417497721131,1:1e-06,1:1e-06)1:3.147048210698639,((C.tcheponensis_TMS,((C.calathiformis_PDLZ,C.fissa_JFL,1:1e-06,1:1e-06)1:3.6168886995733494,(C.mollissima_MJ,(Q.variabilis_SCBG,T.doichangensis_PDLZ,1:1e-06,1:1e-06)1:1.8604848152213187,1:1e-06,1:1e-06)1:3.0480285469045323,1:1e-06,1:1e-06)1:0.8051704619464213,1:1e-06,1:1e-06)1:0.42574316154068037,(C.mekongensis_PDLZ,((C.delavayi_GL,C.jucunda_LA,1:1e-06,1:1e-06)1:0.47376282635867173,((C.sclerophylla_NC,C.chinensis_DH,1:1e-06,1:1e-06)1:0.5138347518433579,(C.clarkei_DHB,((C.hainanensis_JFL,C.Wenchangensis_LFT,1:1e-06,1:1e-06)1:0.2905205642809593,C.indica_JFL,0.79:1e-06,0.79:1e-06)0.79:0.09827179490902768,1:1e-06,1:1e-06)1:1.4238027017781472,0.36:1e-06,0.36:1e-06)0.36:0.0021041858701776844,1:1e-06,1:1e-06)1:2.3447147031764852,0.59:1e-06,0.59:1e-06)0.59:0.0899321128602383,0.7:1e-06,0.7:1e-06)0.7:0.12792376579532222,1:1e-06,1:1e-06)1:0.549593321786997):0.0);

**Comment by tsm-tsm** [comment]
Thank you for your willingness to assist.
Sorry, it was because simulate_gene_trees.py didn't have executable permissions, and due to my carelessness, I mistook sampled_ancestornodes_to_branches.py for simulate_gene_trees.py, which resulted in the program not running successfully. After I reran the following code, the program executed correctly. Thanks again for making this script, it was very helpful.

chmod +x ./tree_utilities-master/simulate_gene_trees.py
./tree_utilities-master/simulate_gene_trees.py astral-BS50-root.treefile 1000 example_gene_trees.tree

**Comment by ryanafolk** [comment]
Ah — right! No problem.

Ryan A. Folk
Assistant Professor and Herbarium Curator
Department of Biological Sciences
Mississippi State University
295 E. Lee Blvd.
P.O. Box GY
Mississippi State, MS 39762
http://www.ryanafolk.com

On May 4, 2024, at 9:55 PM, lilili ***@***.******@***.***>> wrote:



Thank you for your willingness to assist.
Sorry, it was because simulate_gene_trees.py didn't have executable permissions, and due to my carelessness, I mistook sampled_ancestornodes_to_branches.py for simulate_gene_trees.py, which resulted in the program not running successfully. After I reran the following code, the program executed correctly. Thanks again for making this script, it was very helpful.

chmod +x ./tree_utilities-master/simulate_gene_trees.py
./tree_utilities-master/simulate_gene_trees.py astral-BS50-root.treefile 1000 example_gene_trees.tree
